### ISSUE TITLE
Rest API call on linked pull requests

### ISSUE THREAD

**Issue by Ashokg6** [PFacheris/bitbucket-linked-pull-requests#4]
Hi Patrick,

This plugin is very interesting, I have installed it on my bb_server and linked all my PR's under one parent PR .

I'm looking here to get the linked PR's details by using REST API call is it possible to get these all linked Pull requests details through REST Call ? if yes please share me the REST command how to get it ?

BR
Ashok G

**Comment by PFacheris** [comment]
Hi @Ashokg6, there is actually REST API exposed by this plugin.

Here's an example:
```
 $ curl https://my-bitbucket-server.local/rest/linked-pull-requests/latest/projects/MY-PROJECT1/repos/my-repo1/pull-requests/1 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   643    0   643    0     0   4114      0 --:--:-- --:--:-- --:--:--  4121
{
  "links": [
    {
      "id": "1bebf8a8-aa2f-4c0d-a368-bcd0327309f5",
      "direction": "from",
      "slug": "my-repo2",
      "pullRequestId": 394,
      "state": "MERGED",
      "project": "MY-PROJECT2"
    },
    {
      "id": "ebc1e135-e990-448f-a2a5-13f9772b8a6d",
      "direction": "from",
      "slug": "my-repo1",
      "pullRequestId": 2,
      "state": "OPEN",
      "project": "MY-PROJECT1"
    },
    {
      "id": "c7832df4-cbf6-4ba7-84d8-e0e6ee06209b",
      "direction": "from",
      "slug": "my-repo3",
      "pullRequestId": 322,
      "state": "OPEN",
      "project": "MY-PROJECT2"
    },
    {
      "id": "38bfe03a-c762-4b55-a628-88a3e7faee1f",
      "direction": "to",
      "slug": "my-repo4",
      "pullRequestId": 70,
      "state": "OPEN",
      "project": "MY-PROJECT2"
    }
  ]
}
```

Let me know if you'd like any additional info, you can also see this if you inspect the requests during page load using Chrome dev tools or some equivalent.

**Comment by Ashokg6** [comment]
Hi PFacheris ,

This is awesome thank you so much  . I have small concern here along with these details can i get the linked PR's URLs instead of ids so that i can write some restrictions like parent PR should not merge until unless linked PRs got merged .

/usr/bin/curl -k -s -H "Authorization: Bearer MTQ2MjY4NTY0MzI1OkoX1wWN9ciQxukjdyjdePckQ2E0" -H "Content-Type:application/json" http://l42-icx-nexus-01:7990/rest/linked-pull-requests/latest/projects/ICX/repos/poc_repo/pull-requests/2 | /users/home/swrel/bin/jq
{
  "links": [
    {
      **url : http://l42-icx-nexus-01:7990/projects/ICX/repos/ajeytesting/pull-requests/1**
      "id": "854bc97f-4b59-40b6-85b5-11dd2f9723c5",
         "direction": "to",
      "slug": "ajeytesting",
      "pullRequestId": 1,
      "state": "MERGED",
      "project": "ICX"
    },
   
{
      "id": "4d80fad8-40f1-440c-8e06-e2bb54bb34cb",
      "direction": "to",
      "slug": "plugin-test",
      "pullRequestId": 1,
      "state": "OPEN",
      "project": "ICX"
    },
    {
      "id": "06418eb3-9a69-4fb4-9899-f11bc154f42c",
      "direction": "to",
      "slug": "hook_test",
      "pullRequestId": 5,
      "state": "OPEN",
      "project": "ICX"
    }
  ]
}
I want to get the linked PR URL 's along with these details . Please look into .

BR
Ashok G
