### ISSUE TITLE
incompatible with current version (6.2) of BitBucket.

### ISSUE THREAD

**Issue by Briankp** [PFacheris/bitbucket-linked-pull-requests#5]
Your request to update the app has been sent to the vendor.
This is the me.facheris.bitbucket.plugins:linked-pull-requests plugin for Atlassian Bitbucket Server.

This app is not compatible with your Bitbucket instance. An update for this app has already been requested from the vendor.
Uninstall Disable
Loading screenshots...
Version:
0.3
Vendor:
Patrick Facheris
App key:
me.facheris.bitbucket.plugins.linked-pull-requests
4 of 4 modules enabled
Linked Pull Requests link (linked-pull-requests-panel)
Linked Pull Requests Resources (linked-pull-requests-resources)
LinkedPullRequestsModel (linked-pull-requests-rest-resource)
The Linked Pull Requests Rest Resource Plugin
LinkedPullRequestsModel (linked-pull-requests-rest-resource-filter)
The Linked Pull Requests Rest Resource Plugin
![incompatible_with_bitbucket]
![in-compatible_screen_shot](https://user-images.githubusercontent.com/2304564/62827067-af209e00-bb7c-11e9-8df5-617c1cee0288.png)

**Comment by Briankp** [comment]
Please let me know if you can fix this issue right away?
Thanks!

**Comment by PFacheris** [comment]
Just released a new version that's working with Bitbucket 6.x
